version: "3.9"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db 
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    volumes:
      - ./dist/:/usr/app/clean-node-api/dist/
      - ./package.json:/usr/app/clean-node-api/package.json
    command: bash -c "npm install --omit=dev && npm start"
    ports:
      - "5050:5050"
    links:
      - mongo